### 1. General info of dataset GSE223373

This is the Jupyter Notebook for dataset GSE223373. Its dataset includes barcodes/genes/matrix files for each sample. There are 3 samples.
	
GSM7968797	Intraocular RB 1, scRNAseq

GSM7968798	Intraocular RB 2, scRNAseq

GSM7968799	Extraocular RB 1, scRNAseq

GSM7968800	Extraocular RB 2, scRNAseq

In [1]:
# Environment setup
import numpy as np
import pandas as pd
import scanpy as sc
import anndata as anndata
import scipy

### 2. AnnData object of each sample

<span style="color:red">**IMPORTANT:**</span> rename files to get rid of prefixes

1. `barcodes.tsv`: cell barcodes, which go into `.obs`
2. `genes.tsv`: gene names, `.var`
3. `matrix.mtx`: the expression matrix, `.X`

In [2]:
from pathlib import Path

In [7]:
# Specify directory paths
data_directory = Path('/scratch/user/uqjsaxo1/xiaohan-john-project/data/GSE249995_RAW/')
write_directory = Path('/scratch/user/uqjsaxo1/xiaohan-john-project/write/GSE249995/')

# Loop through all files in the directory
for sample_directory in data_directory.iterdir():
    sample_name = sample_directory.stem
    sample_h5ad = sample_name + '_uni.h5ad'

    sample = sc.read_10x_mtx(
    sample_directory,
    var_names='gene_symbols',  
    cache=False
    )

    # Create an observation metric info to store related features
    obs_metrics = pd.DataFrame(index=sample.obs_names) ## Get the identifiers
    obs_metrics['cancer_type'] = 'Retinoblastoma'
    obs_metrics['dataset'] = 'GSE249995'
    obs_metrics['tissue'] = 'Retina'
    obs_metrics['sample_barcode'] = sample_name
    obs_metrics['uni_barcode'] = obs_metrics['dataset'] + '_' + obs_metrics.index.astype(str)
    
    sample.obs = obs_metrics
    sample.obs.set_index("uni_barcode", drop=True, inplace=True)
    print(sample)

    # save the anndata object
    output_path = write_directory.joinpath(sample_h5ad)
    sample.write_h5ad(output_path, compression="gzip")

/home/uqjsaxo1/miniforge3/envs/env/lib/python3.10/site-packages/anndata/utils.py:260: UserWarning: Suffix used (-[0-9]+) to deduplicate index values may make index values difficult to interpret. There values with a similar suffixes in the index. Consider using a different delimiter by passing `join={delimiter}`Example key collisions generated by the make_index_unique algorithm: ['SNORD116-1', 'SNORD116-2', 'SNORD116-3', 'SNORD116-4', 'SNORD116-5']
  warnings.warn(

AnnData object with n_obs × n_vars = 13370 × 60656
    obs: 'cancer_type', 'dataset', 'tissue', 'sample_barcode'
    var: 'gene_ids'
AnnData object with n_obs × n_vars = 11099 × 33538
    obs: 'cancer_type', 'dataset', 'tissue', 'sample_barcode'
    var: 'gene_ids'

/home/uqjsaxo1/miniforge3/envs/env/lib/python3.10/site-packages/anndata/utils.py:260: UserWarning: Suffix used (-[0-9]+) to deduplicate index values may make index values difficult to interpret. There values with a similar suffixes in the index. Consider using a different delimiter by passing `join={delimiter}`Example key collisions generated by the make_index_unique algorithm: ['SNORD116-1', 'SNORD116-2', 'SNORD116-3', 'SNORD116-4', 'SNORD116-5']
  warnings.warn(

AnnData object with n_obs × n_vars = 15386 × 60656
    obs: 'cancer_type', 'dataset', 'tissue', 'sample_barcode'
    var: 'gene_ids'
AnnData object with n_obs × n_vars = 10453 × 36601
    obs: 'cancer_type', 'dataset', 'tissue', 'sample_barcode'
    var: 'gene_ids'

### 3. Confirmation of created AnnData objects

In [10]:
from pathlib import Path

# Specify directory paths
write_directory = Path('/scratch/user/uqjsaxo1/xiaohan-john-project/write/GSE249995/')

# Loop through all files in the directory
for file in write_directory.iterdir():
    sample = anndata.read_h5ad(file)
    print(sample)

AnnData object with n_obs × n_vars = 15386 × 60656
    obs: 'cancer_type', 'dataset', 'tissue', 'sample_barcode'
    var: 'gene_ids'
AnnData object with n_obs × n_vars = 10453 × 36601
    obs: 'cancer_type', 'dataset', 'tissue', 'sample_barcode'
    var: 'gene_ids'
AnnData object with n_obs × n_vars = 11099 × 33538
    obs: 'cancer_type', 'dataset', 'tissue', 'sample_barcode'
    var: 'gene_ids'
AnnData object with n_obs × n_vars = 13370 × 60656
    obs: 'cancer_type', 'dataset', 'tissue', 'sample_barcode'
    var: 'gene_ids'

In [11]:
sample.obs

,cancer_type,dataset,tissue,sample_barcode
uni_barcode,,,,
GSE249995_AAACCCAAGAACTCCT-1,Retinoblastoma,GSE249995,Retina,GSM7968800_ex_RB2
GSE249995_AAACCCAAGCGCCGTT-1,Retinoblastoma,GSE249995,Retina,GSM7968800_ex_RB2
GSE249995_AAACCCAAGGATACAT-1,Retinoblastoma,GSE249995,Retina,GSM7968800_ex_RB2
GSE249995_AAACCCAAGTATAGAC-1,Retinoblastoma,GSE249995,Retina,GSM7968800_ex_RB2
GSE249995_AAACCCACACTCCGGA-1,Retinoblastoma,GSE249995,Retina,GSM7968800_ex_RB2
...,...,...,...,...
GSE249995_TTTGTTGTCCCAACTC-1,Retinoblastoma,GSE249995,Retina,GSM7968800_ex_RB2
GSE249995_TTTGTTGTCGAGATGG-1,Retinoblastoma,GSE249995,Retina,GSM7968800_ex_RB2
GSE249995_TTTGTTGTCGTAGTGT-1,Retinoblastoma,GSE249995,Retina,GSM7968800_ex_RB2
GSE249995_TTTGTTGTCGTTCTGC-1,Retinoblastoma,GSE249995,Retina,GSM7968800_ex_RB2
GSE249995_TTTGTTGTCTAGCCAA-1,Retinoblastoma,GSE249995,Retina,GSM7968800_ex_RB2

In [12]:
sample.var

                      gene_ids
DDX11L1      ENSG00000223972.5
WASH7P       ENSG00000227232.5
MIR6859-1    ENSG00000278267.1
MIR1302-2HG  ENSG00000243485.5
MIR1302-2    ENSG00000284332.1
...                        ...
MT-ND6       ENSG00000198695.2
MT-TE        ENSG00000210194.1
MT-CYB       ENSG00000198727.2
MT-TT        ENSG00000210195.2
MT-TP        ENSG00000210196.2

[60656 rows x 1 columns]

In [14]:
sample.X[1:100, 1:100].toarray()

array([[0., 0., 0., ..., 2., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

### 4. Convert AnnData objects to SingleCellExperiment objects

In [ ]:
from pathlib import Path

import anndata2ri
import rpy2.robjects as robjects
from rpy2.robjects import r
from rpy2.robjects.conversion import localconverter

# Specify directory paths
write_directory = Path('/scratch/user/s4543064/xiaohan-john-project/write/GSE136929')

# Loop through all files in the directory
for file in write_directory.iterdir():
    sample_name = file.stem
    if "_uni.h5ad" in file.name:
        sample_anndata = anndata.read_h5ad(file)
        sample_sce_file = sample_name + ".rds"

        with localconverter(anndata2ri.converter):
            sample_sce = anndata2ri.py2rpy(sample_anndata)
        # print(sample_sce)
        
        # Save the sce object in .rds file
        robjects.globalenv["sample_sce"] = sample_sce
        sample_sce_path = write_directory / sample_sce_file
        robjects.r("saveRDS(sample_sce, file='{}')".format(sample_sce_path))