### 1. General info of dataset PRJNA737188

This is the Jupyter Notebook for dataset PRJNA737188. The raw sequencing data (from two runs) is downloaded and put into Cell Ranger. The resulting filtered_feature_bc_matrix.h5 files are used for processing.

In [25]:
# Environment setup
import numpy as np
import pandas as pd
import scanpy as sc
import anndata as anndata
import scipy

### 2. Inspection of processed AnnData objects

In [26]:
from pathlib import Path

# Specify directory paths
data_directory = Path('/scratch/user/s4543064/xiaohan-john-project/data/PRJNA737188')

SRR14800535_path = data_directory / 'SRR14800535_filtered_feature_bc_matrix.h5'
SRR14800536_path = data_directory / 'SRR14800536_filtered_feature_bc_matrix.h5'

SRR14800535 = sc.read_10x_h5(SRR14800535_path)
SRR14800536 = sc.read_10x_h5(SRR14800536_path)

/home/s4543064/miniforge3/envs/test/lib/python3.12/site-packages/anndata/_core/anndata.py:1908: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/home/s4543064/miniforge3/envs/test/lib/python3.12/site-packages/anndata/_core/anndata.py:1908: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/home/s4543064/miniforge3/envs/test/lib/python3.12/site-packages/anndata/_core/anndata.py:1908: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/home/s4543064/miniforge3/envs/test/lib/python3.12/site-packages/anndata/_core/anndata.py:1908: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")

In [27]:
SRR14800535

AnnData object with n_obs × n_vars = 5577 × 36601
    var: 'gene_ids', 'feature_types', 'genome'

In [28]:
SRR14800535.var

                    gene_ids    feature_types  genome
MIR1302-2HG  ENSG00000243485  Gene Expression  GRCh38
FAM138A      ENSG00000237613  Gene Expression  GRCh38
OR4F5        ENSG00000186092  Gene Expression  GRCh38
AL627309.1   ENSG00000238009  Gene Expression  GRCh38
AL627309.3   ENSG00000239945  Gene Expression  GRCh38
...                      ...              ...     ...
AC141272.1   ENSG00000277836  Gene Expression  GRCh38
AC023491.2   ENSG00000278633  Gene Expression  GRCh38
AC007325.1   ENSG00000276017  Gene Expression  GRCh38
AC007325.4   ENSG00000278817  Gene Expression  GRCh38
AC007325.2   ENSG00000277196  Gene Expression  GRCh38

[36601 rows x 3 columns]

In [29]:
SRR14800535.obs

Empty DataFrame
Columns: []
Index: [AAACCTGAGCCCAATT-1, AAACCTGAGTAGGCCA-1, AAACCTGAGTGCGATG-1, AAACCTGCAAAGTCAA-1, AAACCTGCACCTCGTT-1, AAACCTGCATGGTCAT-1, AAACCTGGTACATGTC-1, AAACCTGGTGGAAAGA-1, AAACCTGGTTGTACAC-1, AAACCTGTCCTCATTA-1, AAACCTGTCGCCATAA-1, AAACCTGTCTACGAGT-1, AAACCTGTCTGGTATG-1, AAACGGGAGCCCAGCT-1, AAACGGGAGCGTAATA-1, AAACGGGCACAGTCGC-1, AAACGGGCACCCATTC-1, AAACGGGCAGACGTAG-1, AAACGGGCAGCTATTG-1, AAACGGGTCAATAAGG-1, AAACGGGTCATTCACT-1, AAACGGGTCGCCGTGA-1, AAAGATGAGATCGGGT-1, AAAGATGCAAGAGGCT-1, AAAGATGCAAGCCCAC-1, AAAGATGCAGCCAGAA-1, AAAGATGCATCGATGT-1, AAAGATGGTACCCAAT-1, AAAGATGGTCCAACTA-1, AAAGATGGTGATGCCC-1, AAAGATGTCCGTAGGC-1, AAAGATGTCGGAGCAA-1, AAAGATGTCGTAGGAG-1, AAAGCAAAGCCACCTG-1, AAAGCAAAGCCGCCTA-1, AAAGCAAAGGATGTAT-1, AAAGCAAAGTCTCAAC-1, AAAGCAAAGTGCCAGA-1, AAAGCAACACATTAGC-1, AAAGCAACACGGTAGA-1, AAAGCAACATAACCTG-1, AAAGCAAGTAATCGTC-1, AAAGCAAGTATGAATG-1, AAAGCAAGTGTTCGAT-1, AAAGCAAGTGTTTGGT-1, AAAGCAATCATACGGT-1, AAAGCAATCCAGTAGT-1, AAAGCAATCGCATGGC-1, AAAGCAATCTAAGCCA-1, AAAGTAGAGAGGTTGC-1, AAAGTAGAGATCCCGC-1, AAAGTAGAGCGAAGGG-1, AAAGTAGCACAGACAG-1, AAAGTAGCACTGCCAG-1, AAAGTAGCACTTGGAT-1, AAAGTAGGTAGAAAGG-1, AAAGTAGTCACGGTTA-1, AAAGTAGTCTCTGCTG-1, AAATGCCAGAAGGCCT-1, AAATGCCAGAGTACCG-1, AAATGCCAGTCAATAG-1, AAATGCCCAGCTATTG-1, AAATGCCCATGCCCGA-1, AAATGCCGTTTGTGTG-1, AAATGCCTCTCATTCA-1, AACACGTAGAAGGCCT-1, AACACGTCAAAGAATC-1, AACACGTCAGTGGAGT-1, AACACGTGTACGACCC-1, AACACGTGTCAAAGCG-1, AACACGTGTCTGCAAT-1, AACACGTTCCTCTAGC-1, AACACGTTCGAACTGT-1, AACACGTTCGCACTCT-1, AACACGTTCTCTGAGA-1, AACCATGAGCCCAATT-1, AACCATGAGCTGTCTA-1, AACCATGAGTGTACCT-1, AACCATGCAAGTTCTG-1, AACCATGCACAGGCCT-1, AACCATGCACCGAAAG-1, AACCATGCATTCCTCG-1, AACCATGTCCAAAGTC-1, AACCATGTCCGTCAAA-1, AACCATGTCCTAAGTG-1, AACCATGTCTACTATC-1, AACCATGTCTCATTCA-1, AACCGCGAGCAGACTG-1, AACCGCGAGCGAGAAA-1, AACCGCGCACCAGATT-1, AACCGCGGTAATCACC-1, AACCGCGGTCAAACTC-1, AACCGCGTCCGAAGAG-1, AACCGCGTCTGCGACG-1, AACCGCGTCTTGCATT-1, AACGTTGAGAAGATTC-1, AACGTTGCATGAGCGA-1, AACGTTGGTACTTCTT-1, AACGTTGTCAACGCTA-1, AACGTTGTCTGTACGA-1, ...]

[5577 rows x 0 columns]

In [30]:
SRR14800536

AnnData object with n_obs × n_vars = 12343 × 36601
    var: 'gene_ids', 'feature_types', 'genome'

In [31]:
SRR14800536.var

                    gene_ids    feature_types  genome
MIR1302-2HG  ENSG00000243485  Gene Expression  GRCh38
FAM138A      ENSG00000237613  Gene Expression  GRCh38
OR4F5        ENSG00000186092  Gene Expression  GRCh38
AL627309.1   ENSG00000238009  Gene Expression  GRCh38
AL627309.3   ENSG00000239945  Gene Expression  GRCh38
...                      ...              ...     ...
AC141272.1   ENSG00000277836  Gene Expression  GRCh38
AC023491.2   ENSG00000278633  Gene Expression  GRCh38
AC007325.1   ENSG00000276017  Gene Expression  GRCh38
AC007325.4   ENSG00000278817  Gene Expression  GRCh38
AC007325.2   ENSG00000277196  Gene Expression  GRCh38

[36601 rows x 3 columns]

In [32]:
SRR14800536.obs

Empty DataFrame
Columns: []
Index: [AAACCTGAGAGTGAGA-1, AAACCTGAGCGAGAAA-1, AAACCTGAGGAGCGAG-1, AAACCTGAGGCAAAGA-1, AAACCTGAGGGTATCG-1, AAACCTGAGTCCATAC-1, AAACCTGAGTCGTTTG-1, AAACCTGAGTGTTAGA-1, AAACCTGCACATGGGA-1, AAACCTGCACGCGAAA-1, AAACCTGCAGGTCCAC-1, AAACCTGCAGTCACTA-1, AAACCTGCATACTACG-1, AAACCTGCATAGACTC-1, AAACCTGGTAGCTCCG-1, AAACCTGGTGTGAATA-1, AAACCTGGTTCAGCGC-1, AAACCTGGTTCCACGG-1, AAACCTGTCATGTCCC-1, AAACCTGTCATTATCC-1, AAACCTGTCCAAGCCG-1, AAACCTGTCCTCAACC-1, AAACCTGTCGCGTTTC-1, AAACCTGTCGTGGACC-1, AAACCTGTCTCGCTTG-1, AAACCTGTCTGCTGCT-1, AAACCTGTCTTCGGTC-1, AAACCTGTCTTGTACT-1, AAACGGGAGACCCACC-1, AAACGGGAGACTAAGT-1, AAACGGGAGATGTCGG-1, AAACGGGAGGGAAACA-1, AAACGGGCAAACGTGG-1, AAACGGGCAATGGTCT-1, AAACGGGCACACGCTG-1, AAACGGGCAGCGATCC-1, AAACGGGCATGATCCA-1, AAACGGGCATTGTGCA-1, AAACGGGGTAAACCTC-1, AAACGGGGTCGAGATG-1, AAACGGGGTCTCTCGT-1, AAACGGGGTCTTTCAT-1, AAACGGGGTGTCGCTG-1, AAACGGGGTTACAGAA-1, AAACGGGGTTCAGTAC-1, AAACGGGTCACAAACC-1, AAACGGGTCACATAGC-1, AAACGGGTCAGCGACC-1, AAACGGGTCTTCATGT-1, AAAGATGAGACAGAGA-1, AAAGATGAGATCCTGT-1, AAAGATGAGCCACGCT-1, AAAGATGAGCCATCGC-1, AAAGATGAGCGTAGTG-1, AAAGATGAGGAGTCTG-1, AAAGATGCACTACAGT-1, AAAGATGCAGACGTAG-1, AAAGATGGTAAAGGAG-1, AAAGATGGTACCAGTT-1, AAAGATGGTCACTGGC-1, AAAGATGGTCTAAAGA-1, AAAGATGGTGCATCTA-1, AAAGATGGTGTGGTTT-1, AAAGATGGTTCCATGA-1, AAAGATGGTTGGTAAA-1, AAAGATGTCAAACCGT-1, AAAGATGTCAAGATCC-1, AAAGATGTCACGATGT-1, AAAGATGTCGTCTGAA-1, AAAGCAAAGAACAATC-1, AAAGCAAAGAGTGAGA-1, AAAGCAAAGATACACA-1, AAAGCAAAGATAGTCA-1, AAAGCAAAGCTGGAAC-1, AAAGCAAAGTGAAGAG-1, AAAGCAACAACACCCG-1, AAAGCAACAAGACACG-1, AAAGCAACACAGAGGT-1, AAAGCAACAGCAGTTT-1, AAAGCAACAGTCAGAG-1, AAAGCAACAGTGAGTG-1, AAAGCAAGTCAAGCGA-1, AAAGCAAGTCGGCATC-1, AAAGCAAGTCGTCTTC-1, AAAGCAAGTCTGCAAT-1, AAAGCAAGTGCAACGA-1, AAAGCAATCAAGGTAA-1, AAAGCAATCACTTACT-1, AAAGCAATCAGTCAGT-1, AAAGCAATCATAAAGG-1, AAAGCAATCATCACCC-1, AAAGCAATCATCTGTT-1, AAAGCAATCCGTCATC-1, AAAGCAATCCTTAATC-1, AAAGCAATCGCCTGTT-1, AAAGCAATCGCTAGCG-1, AAAGCAATCTAACTGG-1, AAAGCAATCTAAGCCA-1, AAAGCAATCTCAAGTG-1, AAAGCAATCTCCTATA-1, ...]

[12343 rows x 0 columns]

### 3. Add feature info in .obs

In [33]:
# load the metadata
age_sex = {
    'SRR14800535': [2, 'male'],
    'SRR14800536': [2, 'female'],
}

In [34]:
write_directory = Path('/scratch/user/s4543064/xiaohan-john-project/write/PRJNA737188')

adatas = (SRR14800535, SRR14800536)

SRR14800535_h5ad = write_directory / 'SRR14800535_uni.h5ad'
SRR14800536_h5ad = write_directory / 'SRR14800536_uni.h5ad'
paths = (SRR14800535_h5ad, SRR14800536_h5ad)

for adata, path in zip(adatas, paths):
    patient_id = path.stem.split('_')[0]

    adata.var.rename_axis('gene_symbols', inplace=True)
    
    adata.obs['cancer_type'] = 'retinoblastoma'
    adata.obs['dataset'] = 'PRJNA737188'
    adata.obs['tissue'] = 'retina'
    adata.obs['age'] = age_sex[patient_id][0]
    adata.obs['sex'] = age_sex[patient_id][1]
    adata.obs['sample_barcode'] = 'PRJNA737188_' + patient_id
    adata.obs['uni_barcode'] = adata.obs['sample_barcode'] + '_' + adata.obs.index
    adata.obs.set_index("uni_barcode", drop=False, inplace=True)

    print(adata)
   
    # Save the modified AnnData objects
    adata.write_h5ad(path, compression="gzip")

AnnData object with n_obs × n_vars = 5577 × 36601
    obs: 'cancer_type', 'dataset', 'tissue', 'age', 'sex', 'sample_barcode', 'uni_barcode'
    var: 'gene_ids', 'feature_types', 'genome'
AnnData object with n_obs × n_vars = 12343 × 36601
    obs: 'cancer_type', 'dataset', 'tissue', 'age', 'sex', 'sample_barcode', 'uni_barcode'
    var: 'gene_ids', 'feature_types', 'genome'

In [35]:
adata.var

                     gene_ids    feature_types  genome
gene_symbols
MIR1302-2HG   ENSG00000243485  Gene Expression  GRCh38
FAM138A       ENSG00000237613  Gene Expression  GRCh38
OR4F5         ENSG00000186092  Gene Expression  GRCh38
AL627309.1    ENSG00000238009  Gene Expression  GRCh38
AL627309.3    ENSG00000239945  Gene Expression  GRCh38
...                       ...              ...     ...
AC141272.1    ENSG00000277836  Gene Expression  GRCh38
AC023491.2    ENSG00000278633  Gene Expression  GRCh38
AC007325.1    ENSG00000276017  Gene Expression  GRCh38
AC007325.4    ENSG00000278817  Gene Expression  GRCh38
AC007325.2    ENSG00000277196  Gene Expression  GRCh38

[36601 rows x 3 columns]

In [36]:
adata.obs

,cancer_type,dataset,tissue,age,sex,sample_barcode,uni_barcode
uni_barcode,,,,,,,
PRJNA737188_SRR14800536_AAACCTGAGAGTGAGA-1,retinoblastoma,PRJNA737188,retina,2,female,PRJNA737188_SRR14800536,PRJNA737188_SRR14800536_AAACCTGAGAGTGAGA-1
PRJNA737188_SRR14800536_AAACCTGAGCGAGAAA-1,retinoblastoma,PRJNA737188,retina,2,female,PRJNA737188_SRR14800536,PRJNA737188_SRR14800536_AAACCTGAGCGAGAAA-1
PRJNA737188_SRR14800536_AAACCTGAGGAGCGAG-1,retinoblastoma,PRJNA737188,retina,2,female,PRJNA737188_SRR14800536,PRJNA737188_SRR14800536_AAACCTGAGGAGCGAG-1
PRJNA737188_SRR14800536_AAACCTGAGGCAAAGA-1,retinoblastoma,PRJNA737188,retina,2,female,PRJNA737188_SRR14800536,PRJNA737188_SRR14800536_AAACCTGAGGCAAAGA-1
PRJNA737188_SRR14800536_AAACCTGAGGGTATCG-1,retinoblastoma,PRJNA737188,retina,2,female,PRJNA737188_SRR14800536,PRJNA737188_SRR14800536_AAACCTGAGGGTATCG-1
...,...,...,...,...,...,...,...
PRJNA737188_SRR14800536_TTTGTCAGTCGAGATG-1,retinoblastoma,PRJNA737188,retina,2,female,PRJNA737188_SRR14800536,PRJNA737188_SRR14800536_TTTGTCAGTCGAGATG-1
PRJNA737188_SRR14800536_TTTGTCAGTTACGGAG-1,retinoblastoma,PRJNA737188,retina,2,female,PRJNA737188_SRR14800536,PRJNA737188_SRR14800536_TTTGTCAGTTACGGAG-1
PRJNA737188_SRR14800536_TTTGTCATCCAATGGT-1,retinoblastoma,PRJNA737188,retina,2,female,PRJNA737188_SRR14800536,PRJNA737188_SRR14800536_TTTGTCATCCAATGGT-1
PRJNA737188_SRR14800536_TTTGTCATCTCCCTGA-1,retinoblastoma,PRJNA737188,retina,2,female,PRJNA737188_SRR14800536,PRJNA737188_SRR14800536_TTTGTCATCTCCCTGA-1
PRJNA737188_SRR14800536_TTTGTCATCTGGAGCC-1,retinoblastoma,PRJNA737188,retina,2,female,PRJNA737188_SRR14800536,PRJNA737188_SRR14800536_TTTGTCATCTGGAGCC-1

### 4. Confirmation of created AnnData objects

In [37]:
from pathlib import Path

write_directory = Path('/scratch/user/s4543064/xiaohan-john-project/write/PRJNA737188')

for file in write_directory.iterdir():
    if '_uni.h5ad' in file.name:
        sample = anndata.read_h5ad(file)
        print(sample)

/home/s4543064/miniforge3/envs/test/lib/python3.12/site-packages/anndata/_core/anndata.py:1908: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")

AnnData object with n_obs × n_vars = 5577 × 36601
    obs: 'cancer_type', 'dataset', 'tissue', 'age', 'sex', 'sample_barcode', 'uni_barcode'
    var: 'gene_ids', 'feature_types', 'genome'
AnnData object with n_obs × n_vars = 12343 × 36601
    obs: 'cancer_type', 'dataset', 'tissue', 'age', 'sex', 'sample_barcode', 'uni_barcode'
    var: 'gene_ids', 'feature_types', 'genome'

/home/s4543064/miniforge3/envs/test/lib/python3.12/site-packages/anndata/_core/anndata.py:1908: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")

In [38]:
sample.var

                     gene_ids    feature_types  genome
gene_symbols
MIR1302-2HG   ENSG00000243485  Gene Expression  GRCh38
FAM138A       ENSG00000237613  Gene Expression  GRCh38
OR4F5         ENSG00000186092  Gene Expression  GRCh38
AL627309.1    ENSG00000238009  Gene Expression  GRCh38
AL627309.3    ENSG00000239945  Gene Expression  GRCh38
...                       ...              ...     ...
AC141272.1    ENSG00000277836  Gene Expression  GRCh38
AC023491.2    ENSG00000278633  Gene Expression  GRCh38
AC007325.1    ENSG00000276017  Gene Expression  GRCh38
AC007325.4    ENSG00000278817  Gene Expression  GRCh38
AC007325.2    ENSG00000277196  Gene Expression  GRCh38

[36601 rows x 3 columns]

In [39]:
sample.obs

,cancer_type,dataset,tissue,age,sex,sample_barcode,uni_barcode
uni_barcode,,,,,,,
PRJNA737188_SRR14800536_AAACCTGAGAGTGAGA-1,retinoblastoma,PRJNA737188,retina,2,female,PRJNA737188_SRR14800536,PRJNA737188_SRR14800536_AAACCTGAGAGTGAGA-1
PRJNA737188_SRR14800536_AAACCTGAGCGAGAAA-1,retinoblastoma,PRJNA737188,retina,2,female,PRJNA737188_SRR14800536,PRJNA737188_SRR14800536_AAACCTGAGCGAGAAA-1
PRJNA737188_SRR14800536_AAACCTGAGGAGCGAG-1,retinoblastoma,PRJNA737188,retina,2,female,PRJNA737188_SRR14800536,PRJNA737188_SRR14800536_AAACCTGAGGAGCGAG-1
PRJNA737188_SRR14800536_AAACCTGAGGCAAAGA-1,retinoblastoma,PRJNA737188,retina,2,female,PRJNA737188_SRR14800536,PRJNA737188_SRR14800536_AAACCTGAGGCAAAGA-1
PRJNA737188_SRR14800536_AAACCTGAGGGTATCG-1,retinoblastoma,PRJNA737188,retina,2,female,PRJNA737188_SRR14800536,PRJNA737188_SRR14800536_AAACCTGAGGGTATCG-1
...,...,...,...,...,...,...,...
PRJNA737188_SRR14800536_TTTGTCAGTCGAGATG-1,retinoblastoma,PRJNA737188,retina,2,female,PRJNA737188_SRR14800536,PRJNA737188_SRR14800536_TTTGTCAGTCGAGATG-1
PRJNA737188_SRR14800536_TTTGTCAGTTACGGAG-1,retinoblastoma,PRJNA737188,retina,2,female,PRJNA737188_SRR14800536,PRJNA737188_SRR14800536_TTTGTCAGTTACGGAG-1
PRJNA737188_SRR14800536_TTTGTCATCCAATGGT-1,retinoblastoma,PRJNA737188,retina,2,female,PRJNA737188_SRR14800536,PRJNA737188_SRR14800536_TTTGTCATCCAATGGT-1
PRJNA737188_SRR14800536_TTTGTCATCTCCCTGA-1,retinoblastoma,PRJNA737188,retina,2,female,PRJNA737188_SRR14800536,PRJNA737188_SRR14800536_TTTGTCATCTCCCTGA-1
PRJNA737188_SRR14800536_TTTGTCATCTGGAGCC-1,retinoblastoma,PRJNA737188,retina,2,female,PRJNA737188_SRR14800536,PRJNA737188_SRR14800536_TTTGTCATCTGGAGCC-1

### 5. Convert AnnData objects to SingleCellExperiment objects

In [40]:
from pathlib import Path

import anndata2ri
import rpy2.robjects as robjects
from rpy2.robjects import r
from rpy2.robjects.conversion import localconverter

# Specify directory paths
write_directory = Path('/scratch/user/s4543064/xiaohan-john-project/write/PRJNA737188')

# Loop through all files in the directory
for file in write_directory.iterdir():
    sample_name = file.stem
    if "_uni.h5ad" in file.name:
        sample_anndata = anndata.read_h5ad(file)
        sample_sce_file = sample_name + ".rds"

        with localconverter(anndata2ri.converter):
            sample_sce = anndata2ri.py2rpy(sample_anndata)
            print(sample_sce)
        
        # Save the sce object in .rds file
        robjects.globalenv["sample_sce"] = sample_sce
        sample_sce_path = write_directory / sample_sce_file
        robjects.r("saveRDS(sample_sce, file='{}')".format(sample_sce_path))

/home/s4543064/miniforge3/envs/test/lib/python3.12/site-packages/anndata/_core/anndata.py:1908: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/home/s4543064/miniforge3/envs/test/lib/python3.12/functools.py:909: UserWarning: Duplicated var_names: Index(['ARMCX5-GPRASP2', 'ARMCX5-GPRASP2', 'CYB561D2', 'CYB561D2', 'GGT1',
       'GGT1', 'GOLGA8M', 'GOLGA8M', 'HSPA14', 'HSPA14', 'LINC01238',
       'LINC01238', 'LINC01505', 'LINC01505', 'MATR3', 'MATR3', 'TBCE', 'TBCE',
       'TMSB15B', 'TMSB15B'],
      dtype='object', name='gene_symbols')
  return dispatch(args[0].__class__)(*args, **kw)

class: SingleCellExperiment
dim: 36601 5577
metadata(0):
assays(1): X
rownames(36601): MIR1302-2HG FAM138A ... AC007325.4 AC007325.2
rowData names(3): gene_ids feature_types genome
colnames(5577): PRJNA737188_SRR14800535_AAACCTGAGCCCAATT-1
  PRJNA737188_SRR14800535_AAACCTGAGTAGGCCA-1 ...
  PRJNA737188_SRR14800535_TTTGTCATCGTACGGC-1
  PRJNA737188_SRR14800535_TTTGTCATCTTTCCTC-1
colData names(7): cancer_type dataset ... sample_barcode uni_barcode
reducedDimNames(0):
mainExpName: NULL
altExpNames(0):

/home/s4543064/miniforge3/envs/test/lib/python3.12/site-packages/anndata/_core/anndata.py:1908: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/home/s4543064/miniforge3/envs/test/lib/python3.12/functools.py:909: UserWarning: Duplicated var_names: Index(['ARMCX5-GPRASP2', 'ARMCX5-GPRASP2', 'CYB561D2', 'CYB561D2', 'GGT1',
       'GGT1', 'GOLGA8M', 'GOLGA8M', 'HSPA14', 'HSPA14', 'LINC01238',
       'LINC01238', 'LINC01505', 'LINC01505', 'MATR3', 'MATR3', 'TBCE', 'TBCE',
       'TMSB15B', 'TMSB15B'],
      dtype='object', name='gene_symbols')
  return dispatch(args[0].__class__)(*args, **kw)

class: SingleCellExperiment
dim: 36601 12343
metadata(0):
assays(1): X
rownames(36601): MIR1302-2HG FAM138A ... AC007325.4 AC007325.2
rowData names(3): gene_ids feature_types genome
colnames(12343): PRJNA737188_SRR14800536_AAACCTGAGAGTGAGA-1
  PRJNA737188_SRR14800536_AAACCTGAGCGAGAAA-1 ...
  PRJNA737188_SRR14800536_TTTGTCATCTCCCTGA-1
  PRJNA737188_SRR14800536_TTTGTCATCTGGAGCC-1
colData names(7): cancer_type dataset ... sample_barcode uni_barcode
reducedDimNames(0):
mainExpName: NULL
altExpNames(0):